### ISSUE TITLE
No Chat function/history visible in 5.7

### ISSUE THREAD

**Issue by Bremskerl** [muchino/confluence.chat#108]
we installed chat in actual version 5.7. it seems to work, but there is no readable chat (history). No chat texts are shown anywhere... also text boxes are transparent...

**Comment by muchino** [comment]
you are in the chatboxes? may you can create an image to describe what you mean? 
What xou mean with "no readable chat histories?"

**Comment by muchino** [comment]
you can send me images and log files to: o.straesser.atlassian@gmail.com

**Comment by Bremskerl** [comment]
Kann ich auch auf Deutsch schreiben?

anbei ein Bild...
transparence.... and after "enter" you see nothing.... even in the chat history.


[cid:a049b954-3e0b-4a70-8970-d5e9f16354a7]


________________________________
Von: Oliver Straesser [notifications@github.com]
Gesendet: Dienstag, 24. Februar 2015 21:18
An: muchino/confluence.chat
Cc: Schwessinger, Michael
Betreff: Re: [confluence.chat] No Chat function/history visible in 5.7 (#108)


you are in the chatboxes? may you can create an image to describe what you mean?
What xou mean with "no readable chat histories?"

**Comment by muchino** [comment]
Klar kannst auf deutsch schreiben...  Ich muss mal auf bitbucket wechseln,
denn ich sehe dein embedded Bild nicht.  Kannst du es mir direkt schicken?
O.straesser.atlassian@gmail.com

Bremskerl <notifications@github.com> schrieb am Di., 24.02.2015, 21:52:

**Comment by Bremskerl** [comment]
mails auf gmail erhalten?
________________________________
Von: Oliver Straesser [notifications@github.com]
Gesendet: Dienstag, 24. Februar 2015 21:55
An: muchino/confluence.chat
Cc: Schwessinger, Michael
Betreff: Re: [confluence.chat] No Chat function/history visible in 5.7 (#108)

Klar kannst auf deutsch schreiben... Ich muss mal auf bitbucket wechseln,
denn ich sehe dein embedded Bild nicht. Kannst du es mir direkt schicken?
O.straesser.atlassian@gmail.com

Bremskerl <notifications@github.com> schrieb am Di., 24.02.2015, 21:52:

> Kann ich auch auf Deutsch schreiben?
>
> anbei ein Bild...
> transparence.... and after "enter" you see nothing.... even in the chat
> history.
>
>
> [cid:a049b954-3e0b-4a70-8970-d5e9f16354a7]
>
>
> ________________________________
> Von: Oliver Straesser [notifications@github.com]
> Gesendet: Dienstag, 24. Februar 2015 21:18
> An: muchino/confluence.chat
> Cc: Schwessinger, Michael
> Betreff: Re: [confluence.chat] No Chat function/history visible in 5.7
> (#108)
>
>
> you are in the chatboxes? may you can create an image to describe what you
> mean?
> What xou mean with "no readable chat histories?"
>
> �
> Reply to this email directly or view it on GitHub<
> https://github.com/muchino/confluence.chat/issues/108#issuecomment-75837055
> >.
>
> �
> Reply to this email directly or view it on GitHub
> <https://github.com/muchino/confluence.chat/issues/108#issuecomment-75843320>
> .
>

�

**Comment by muchino** [comment]
Jup

Bremskerl <notifications@github.com> schrieb am Di., 24.02.2015, 22:37:

**Comment by atwleung** [comment]
I have just installed it on Confluence 5.7, and witnessed the same. That is, whatever I typed didn't show up in the chat box, even if I pressed return button. But the plugin can allow me to see which users are online, which is quite awesome already. Thanks for the good work.

**Comment by nfahr** [comment]
After updating to 2.0.5, following errors are logged:

--------------------------
Parameters
--------------------------
status : chat
pageId : null
currentTitle : Übersicht - Confluence
spaceKey : 
_ : 1424871514198
currentUrl : https://confluence.domain.com/dashboard.action
caused by: javax.servlet.ServletException: Servlet execution threw an exception
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:326)
caused by: java.lang.NoSuchMethodError: confluence.chat.model.ChatBoxMap.keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView;
at confluence.chat.actions.AbstractChatAction.start(AbstractChatAction.java:85)

**Comment by muchino** [comment]
Hi nfar, please create a new ticket, because it has no context to this
discussion.
Please write me in addition from which version you upgraded, which
confluence version

nfahr <notifications@github.com> schrieb am Mi., 25.02.2015, 14:50:

**Comment by muchino** [comment]
ok nfar, after I saw the logs from Bremskerl, I have to say: You are right - same error, sorry for that...

**Comment by muchino** [comment]
I found the issue, an update will available soon

**Comment by Bremskerl** [comment]
Super!!!
Vielen Dank!

Gr��e
Michael Schwessinger

**Comment by muchino** [comment]
ist online, ich hoffe es geht nun alles wieder, ich konnte den nicht chat fehler nachvollziehen und bei mir fixen.

**Comment by SteffiF** [comment]
brilliant!!!!! Works!!!!! Many, many thanks!

**Comment by muchino** [comment]
great to hear :)

**Comment by atwleung** [comment]
It works with 2.0.6, just tried, thanks!
